<?php
declare(strict_types=1);

return [
    [
        'id'       => 1,
        'name'     => 'Hotel Thermal',
        'city'     => 'Karlovy Vary',
        'date_from'=> '2026-09-26',
        'date_to'  => '2026-09-27',
        'type'     => 'hala',
    ],
    [
        'id'       => 2,
        'name'     => 'Zámek',
        'city'     => 'Litomyšl',
        'date_from'=> '2026-10-03',
        'date_to'  => '2026-10-04',
        'type'     => 'hala',
    ],
    [
        'id'       => 3,
        'name'     => 'Galerie Teplice',
        'city'     => 'Teplice',
        'date_from'=> '2026-10-09',
        'date_to'  => '2026-10-11',
        'type'     => 'oc',
    ],
    [
        'id'       => 4,
        'name'     => 'Galerie Harfa',
        'city'     => 'Praha',
        'date_from'=> '2026-10-16',
        'date_to'  => '2026-10-18',
        'type'     => 'oc',
    ],
    [
        'id'       => 5,
        'name'     => 'Gečko',
        'city'     => 'České Budějovice',
        'date_from'=> '2026-10-23',
        'date_to'  => '2026-10-25',
        'type'     => 'hala',
    ],
    [
        'id'       => 6,
        'name'     => 'Zámek',
        'city'     => 'Valtice',
        'date_from'=> '2026-10-31',
        'date_to'  => '2026-11-01',
        'type'     => 'hala',
    ],
    [
        'id'       => 7,
        'name'     => 'OC CityPark',
        'city'     => 'Jihlava',
        'date_from'=> '2027-01-22',
        'date_to'  => '2027-01-24',
        'type'     => 'oc',
    ],
    [
        'id'       => 8,
        'name'     => 'Černá Louka',
        'city'     => 'Ostrava',
        'date_from'=> '2027-02-06',
        'date_to'  => '2027-02-07',
        'type'     => 'hala',
    ],
    [
        'id'       => 9,
        'name'     => 'OC Šantovka',
        'city'     => 'Olomouc',
        'date_from'=> '2027-02-12',
        'date_to'  => '2027-02-14',
        'type'     => 'oc',
    ],
    [
        'id'       => 10,
        'name'     => 'OC Palác',
        'city'     => 'Pardubice',
        'date_from'=> '2027-02-12',
        'date_to'  => '2027-02-14',
        'type'     => 'oc',
    ],
    [
        'id'       => 11,
        'name'     => 'Výstaviště',
        'city'     => 'Brno',
        'date_from'=> '2027-02-27',
        'date_to'  => '2027-02-28',
        'type'     => 'hala',
    ],
    [
        'id'       => 12,
        'name'     => 'OC Olympia',
        'city'     => 'Plzeň',
        'date_from'=> '2027-03-05',
        'date_to'  => '2027-03-07',
        'type'     => 'oc',
    ],
    [
        'id'       => 13,
        'name'     => 'Výstaviště',
        'city'     => 'Kroměříž',
        'date_from'=> '2027-03-13',
        'date_to'  => '2027-03-14',
        'type'     => 'hala',
    ],
    [
        'id'       => 14,
        'name'     => 'OC Nisa',
        'city'     => 'Liberec',
        'date_from'=> '2027-03-19',
        'date_to'  => '2027-03-20',
        'type'     => 'oc',
    ],
    [
        'id'       => 15,
        'name'     => 'Zámek',
        'city'     => 'Slavkov u Brna',
        'date_from'=> '2027-04-17',
        'date_to'  => '2027-04-18',
        'type'     => 'hala',
    ],
];